2024-07-24 18:43:13,215 - api.utils.logger - ERROR - Exception occured; too many values to unpack (expected 3)
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 269, in app
    solved_result = await solve_dependencies(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\dependencies\utils.py", line 628, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\dependencies\utils.py", line 758, in request_body_to_args
    v_, errors_ = field.validate(value, values, loc=loc)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\_compat.py", line 127, in validate
    self._type_adapter.validate_python(value, from_attributes=True),
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\pydantic\type_adapter.py", line 373, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
  File "C:\Users\ABDULAZIZ NURA KANI\AppData\Local\Programs\Python\Python310\lib\cgitb.py", line 194, in text
    etype, evalue, etb = einfo
ValueError: too many values to unpack (expected 3)
2024-07-24 18:45:02,709 - api.utils.logger - ERROR - Exception occured; too many values to unpack (expected 3)
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 269, in app
    solved_result = await solve_dependencies(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\dependencies\utils.py", line 628, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\dependencies\utils.py", line 758, in request_body_to_args
    v_, errors_ = field.validate(value, values, loc=loc)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\_compat.py", line 127, in validate
    self._type_adapter.validate_python(value, from_attributes=True),
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\pydantic\type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\pydantic\type_adapter.py", line 373, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
  File "C:\Users\ABDULAZIZ NURA KANI\AppData\Local\Programs\Python\Python310\lib\cgitb.py", line 194, in text
    etype, evalue, etb = einfo
ValueError: too many values to unpack (expected 3)
2024-07-24 18:57:13,465 - api.utils.logger - ERROR - Exception occured; 'fullname' is an invalid keyword argument for ContactUs
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\api\v1\routes\contact_us.py", line 20, in register_specific_contact_msg
    new_contact_msg = ContactUs(**schema.model_dump())
  File "<string>", line 4, in __init__
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 2167, in _declarative_constructor
    raise TypeError(
TypeError: 'fullname' is an invalid keyword argument for ContactUs
2024-07-24 19:03:29,136 - api.utils.logger - ERROR - Exception occured; HTTPException.__init__() got an unexpected keyword argument 'response'
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\api\v1\routes\contact_us.py", line 34, in get_specific_contact_msg
    return HTTPException(status_code=status.HTTP_404_NOT_FOUND,response="contact message not found")
TypeError: HTTPException.__init__() got an unexpected keyword argument 'response'
2024-07-24 19:06:19,170 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}

2024-07-24 19:07:48,420 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}

2024-07-24 19:09:01,023 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': HTTPException(status_code=404, detail='contact message with ID: 066a1016-aa2f-759f-8000-2af7896e6708 not found')}

2024-07-24 19:12:40,472 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x0000019CB7BABD60>}}

2024-07-24 19:18:16,991 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': <api.v1.models.contact_us.ContactUs object at 0x00000218A3DB3D60>}}

2024-07-24 19:24:14,409 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': {'Full name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}

2024-07-24 19:43:10,584 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}

2024-07-24 19:44:03,096 - api.utils.logger - ERROR - Exception occured; 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 296, in app
    content = await serialize_response(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 155, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'full_name'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'email'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}
  {'type': 'missing', 'loc': ('response', 'message'), 'msg': 'Field required', 'input': {'data': {'full_name': '066a1016-aa2f-759f-8000-2af7896e6708', 'email': 'user@example.com', 'title': 'string', 'message': 'string'}}}

2024-07-24 20:08:40,235 - api.utils.logger - ERROR - Exception occured; 'User' object is not subscriptable
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\api\v1\routes\contact_us.py", line 37, in get_specific_contact_msg
    if not user['is_superadmin']:
TypeError: 'User' object is not subscriptable
2024-07-24 20:09:17,086 - api.utils.logger - ERROR - Exception occured; 'User' object has no attribute 'is_superadmin'
Traceback (most recent call last):
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "c:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\ABDULAZIZ NURA KANI\Desktop\STAGE 5\hng_boilerplate_python_fastapi_web\api\v1\routes\contact_us.py", line 37, in get_specific_contact_msg
    if not user.is_superadmin:
AttributeError: 'User' object has no attribute 'is_superadmin'. Did you mean: 'is_super_admin'?
